application: clock
version: 1
runtime: python27
api_version: 1
threadsafe: true

# we could either define our URL paths here or inside the WSGI instance.
handlers:
- url: /prefs
  script: prefs.application
  login: required

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"


